language: python
python:
  - "3.4"

sudo: false
cache: pip

install:
  - python setup.py install
  - pip install -rdev-requirements.txt
  - pip install coveralls

script:
    - py.test -v -s tests --cov gns3server --cov-report term-missing

#branches:
#  only:
#    - master

notifications:
  email:
    - julien@gns3.net
#  irc:
#    channels:
#      - "chat.freenode.net#gns3"
#    on_success: change
#    on_failure: always

after_success:
  - coveralls
